language: groovy
jdk:
  - oraclejdk7
env:
- GRAILS_VERSION=2.2.2
- GRAILS_VERSION=2.2.5
- GRAILS_VERSION=2.3.11
- GRAILS_VERSION=2.4.5
- GRAILS_VERSION=2.5.5

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
  - master
before_script:
 - chmod +x grailsw
script: ./grailsw clean; ./grailsw test-app --unit; ./grailsw package-plugin;
