language: groovy
jdk:
  - oraclejdk7
env:
- GRAILS_VERSION=2.2.2
- GRAILS_VERSION=2.2.5
- GRAILS_VERSION=2.3.11
- GRAILS_VERSION=2.4.5
- GRAILS_VERSION=2.5.0
- GRAILS_VERSION=2.5.4

before_install:
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails $GRAILS_VERSION

branches:
  only:
  - master

script:
    - ./ci.sh
