import grails.test.AbstractCliTestCase

/**
 * Run with: test-app --other
 * See target/cli-output for any output generated by the script
 * CLI script testing
 * http://www.cacoethes.co.uk/blog/groovyandgrails/testing-your-grails-scripts
 */
class SplitTestScriptTests extends AbstractCliTestCase{

    @Override
    protected void setUp() {
        timeout = 10000
    }

    @Override
    protected void tearDown() {
        println """
--------------------------------Script output---------------------
${output}
"""
    }

    void testCommandLineArgs(){
        execute(['split-test'])
        assert 0 == waitForProcess()

        verifyHeader()
    }
}

